export const CREATE_CUSTOM_BOUQUET_REQUEST = 'CREATE_CUSTOM_BOUQUET_REQUEST';
export const CREATE_CUSTOM_BOUQUET_SUCCESS = 'CREATE_CUSTOM_BOUQUET_SUCCESS';
export const CREATE_CUSTOM_BOUQUET_FAIL = 'CREATE_CUSTOM_BOUQUET_FAIL';

export const GET_CUSTOM_BOUQUET_REQUEST = 'GET_CUSTOM_BOUQUET_REQUEST';
export const GET_CUSTOM_BOUQUET_SUCCESS = 'GET_CUSTOM_BOUQUET_SUCCESS';
export const GET_CUSTOM_BOUQUET_FAIL = 'GET_CUSTOM_BOUQUET_FAIL';

export const ADD_PRODUCTS_TO_CUSTOM_BOUQUET_REQUEST = 'ADD_PRODUCTS_TO_CUSTOM_BOUQUET_REQUEST';
export const ADD_PRODUCTS_TO_CUSTOM_BOUQUET_SUCCESS = 'ADD_PRODUCTS_TO_CUSTOM_BOUQUET_SUCCESS';
export const ADD_PRODUCTS_TO_CUSTOM_BOUQUET_FAIL = 'ADD_PRODUCTS_TO_CUSTOM_BOUQUET_FAIL';
