export const CREATE_RESTOCK_REQUEST = 'CREATE_RESTOCK_REQUEST';
export const CREATE_RESTOCK_SUCCESS = 'CREATE_RESTOCK_SUCCESS';
export const CREATE_RESTOCK_FAIL = 'CREATE_RESTOCK_FAIL';

export const GET_ALL_RESTOCKS_REQUEST = 'GET_ALL_RESTOCKS_REQUEST';
export const GET_ALL_RESTOCKS_SUCCESS = 'GET_ALL_RESTOCKS_SUCCESS';
export const GET_ALL_RESTOCKS_FAIL = 'GET_ALL_RESTOCKS_FAIL';

export const GET_RESTOCK_BY_ID_REQUEST = 'GET_RESTOCK_BY_ID_REQUEST';
export const GET_RESTOCK_BY_ID_SUCCESS = 'GET_RESTOCK_BY_ID_SUCCESS';
export const GET_RESTOCK_BY_ID_FAIL = 'GET_RESTOCK_BY_ID_FAIL';