export const SHIFT_LIST_REQUEST = 'SHIFT_LIST_REQUEST';
export const SHIFT_LIST_SUCCESS = 'SHIFT_LIST_SUCCESS';
export const SHIFT_LIST_FAIL = 'SHIFT_LIST_FAIL';

export const SHIFT_ADD_REQUEST = 'SHIFT_ADD_REQUEST';
export const SHIFT_ADD_SUCCESS = 'SHIFT_ADD_SUCCESS';
export const SHIFT_ADD_FAIL = 'SHIFT_ADD_FAIL';

export const CREATE_SHIFT_REQUEST = 'CREATE_SHIFT_REQUEST';
export const CREATE_SHIFT_SUCCESS = 'CREATE_SHIFT_SUCCESS';
export const CREATE_SHIFT_FAIL = 'CREATE_SHIFT_FAIL';

export const SCHEDULE_FETCH_REQUEST = 'SCHEDULE_FETCH_REQUEST';
export const SCHEDULE_FETCH_SUCCESS = 'SCHEDULE_FETCH_SUCCESS';
export const SCHEDULE_FETCH_FAIL = 'SCHEDULE_FETCH_FAIL';